name: Build and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create lib directory
      run: mkdir -p lib
      
    - name: Download dependencies before firewall restrictions
      run: |
        # Download showdown.min.js
        curl -s https://cdn.jsdelivr.net/npm/showdown@2.1.0/dist/showdown.min.js -o lib/showdown.min.js
        
        # Download other potentially needed dependencies
        curl -s https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css -o lib/bootstrap.min.css
        curl -s https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js -o lib/bootstrap.bundle.min.js
        curl -s https://cdn.jsdelivr.net/npm/chart.js@4.3.0/dist/chart.min.js -o lib/chart.min.js
        
        # Verify downloads
        ls -la lib/
        
    - name: Validate downloaded files
      run: |
        # Check that files were downloaded successfully
        if [ ! -f "lib/showdown.min.js" ]; then
          echo "Error: showdown.min.js not downloaded"
          exit 1
        fi
        
        if [ ! -s "lib/showdown.min.js" ]; then
          echo "Error: showdown.min.js is empty"
          exit 1
        fi
        
        echo "All dependencies downloaded successfully"
        
    - name: Test HTML file validity
      run: |
        # Basic validation that HTML file exists and contains expected content
        if [ ! -f "index.html" ]; then
          echo "Error: index.html not found"
          exit 1
        fi
        
        echo "Build completed successfully"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: elasticsearch-gui-build
        path: |
          .
          !.git
          !.github